const path=require('path');require('dotenv').config();const express=require('express');const session=require('express-session');const cron=require('node-cron');const crypto=require('crypto');
const authRoutes=require('./routes/auth');const {ensureToken}=require('./routes/auth');const apiRoutes=require('./routes/api');const {analyzeAccount}=require('./services/processor');const {loadConfig,saveConfig}=require('./services/config');const {loadAuth,initStorage}=require('./services/storage');const {ensureFreshAuth,syncAuthToSession}=require('./services/token');
const app=express(),PORT=process.env.PORT||3000;app.set('trust proxy',1);app.use(express.urlencoded({extended:true}));app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex'),resave:false,saveUninitialized:false,cookie:{maxAge:7*24*60*60*1000,httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));app.set('view engine','ejs');app.set('views',path.join(__dirname,'views'));
function privateGuard(req,res,next){if(req.path==='/private-login'||req.session.private_ok)return next();return res.redirect('/private-login')}
app.get('/private-login',(req,res)=>res.render('login',{error:req.query.error||null}));app.post('/private-login',(req,res)=>{const expected=String(process.env.APP_PASSWORD||'');if(!expected)return res.status(500).send('APP_PASSWORD não configurada');const a=Buffer.from(String(req.body.password||'')),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.redirect('/private-login?error=Senha inválida');req.session.private_ok=true;res.redirect('/')});app.use(privateGuard);app.use('/auth',authRoutes);app.use('/api',apiRoutes);
app.get('/',async(req,res)=>{let saved=await loadAuth(),restoreError=null;if(!req.session.access_token&&saved?.refresh_token){try{saved=await ensureFreshAuth(saved);syncAuthToSession(saved,req.session)}catch(e){restoreError='A autorização do Mercado Livre precisa ser renovada.'}}const config=await loadConfig();res.render('index',{isAuthenticated:!!req.session.access_token,hasSavedAuth:!!saved?.refresh_token,user:req.session.user||saved?.user||null,config,message:req.query.message||null,error:req.query.error||restoreError})});
app.post('/config',ensureToken,async(req,res)=>{const cronSchedule=String(req.body.cronSchedule||'0 9 * * *').trim();if(req.body.scheduledAnalysis==='on'&&!cron.validate(cronSchedule))return res.redirect('/?error=Expressão cron inválida');await saveConfig({lookbackDays:Math.max(7,parseInt(req.body.lookbackDays)||30),minAgeDays:Math.max(0,parseInt(req.body.minAgeDays)||30),lowVisits30:Math.max(0,parseInt(req.body.lowVisits30)||25),highVisits30:Math.max(1,parseInt(req.body.highVisits30)||200),minScore:Math.min(100,Math.max(1,parseInt(req.body.minScore)||55)),competitorLimit:Math.min(20,Math.max(3,parseInt(req.body.competitorLimit)||12)),competitorMinSample:Math.min(10,Math.max(3,parseInt(req.body.competitorMinSample)||4)),marketplaceFeePct:Math.max(0,Number(req.body.marketplaceFeePct||0)),taxPct:Math.max(0,Number(req.body.taxPct||0)),fixedFee:Math.max(0,Number(req.body.fixedFee||0)),packagingCost:Math.max(0,Number(req.body.packagingCost||0)),minMarginPct:Math.max(0,Number(req.body.minMarginPct||15)),maxPriceDropPct:Math.min(20,Math.max(0,Number(req.body.maxPriceDropPct||5))),scheduledAnalysis:req.body.scheduledAnalysis==='on',cronSchedule});await setupCron();res.redirect('/?message=Configurações salvas.')});
let cronJob=null;async function setupCron(){if(cronJob){cronJob.stop();cronJob=null}const c=await loadConfig();if(!c.scheduledAnalysis||!cron.validate(c.cronSchedule))return;cronJob=cron.schedule(c.cronSchedule,async()=>{try{const saved=await loadAuth();if(!saved)return;const auth=await ensureFreshAuth(saved);await analyzeAccount(auth,{runType:'scheduled-analysis'})}catch(e){console.error('[CRON]',e.message)}})}
initStorage().then(async()=>{await setupCron();app.listen(PORT,()=>console.log(`Meli Auto Online na porta ${PORT}`))}).catch(e=>{console.error('Falha ao iniciar banco:',e);process.exit(1)});
