const express=require('express');const crypto=require('crypto');const router=express.Router();
const {getAuthUrl,exchangeCode,MeliClient}=require('../services/meli');const {saveAuth,clearAuth,loadAuth}=require('../services/storage');const {ensureFreshAuth,sessionToAuth,syncAuthToSession}=require('../services/token');
function cfg(){return{appId:process.env.MELI_APP_ID,clientSecret:process.env.MELI_CLIENT_SECRET,redirectUri:process.env.MELI_REDIRECT_URI}}
router.get('/login',(req,res)=>{const {appId,clientSecret,redirectUri}=cfg();if(!appId||!clientSecret||!redirectUri)return res.redirect('/?error=Variáveis do Mercado Livre não configuradas no servidor');const state=crypto.randomBytes(24).toString('hex');req.session.oauth_state=state;req.session.oauth_started_at=Date.now();res.redirect(getAuthUrl(appId,redirectUri,state))});
router.get('/callback',async(req,res)=>{const {code,error,error_description,state}=req.query;if(error)return res.redirect(`/?error=${encodeURIComponent(error_description||error)}`);if(!code)return res.redirect('/?error=Código OAuth não recebido');if(!state||state!==req.session.oauth_state)return res.redirect('/?error=State OAuth inválido');if(Date.now()-Number(req.session.oauth_started_at||0)>15*60*1000)return res.redirect('/?error=Autorização expirada. Conecte novamente.');try{const {appId,clientSecret,redirectUri}=cfg();const t=await exchangeCode(code,appId,clientSecret,redirectUri);const me=await new MeliClient(t.access_token).getMe();const auth={access_token:t.access_token,refresh_token:t.refresh_token,expires_at:Date.now()+Number(t.expires_in||0)*1000,user:{id:me.id,nickname:me.nickname,first_name:me.first_name,email:me.email}};await saveAuth(auth);syncAuthToSession(auth,req.session);delete req.session.oauth_state;delete req.session.oauth_started_at;res.redirect('/?message=Conta Mercado Livre conectada com sucesso.')}catch(e){console.error(e.response?.data||e);res.redirect(`/?error=${encodeURIComponent(e.response?.data?.message||e.message)}`)}});
router.get('/restore',async(req,res)=>{try{const a=await loadAuth();if(!a)return res.redirect('/?error=Nenhuma conexão salva');const fresh=await ensureFreshAuth(a);syncAuthToSession(fresh,req.session);res.redirect('/')}catch(e){res.redirect(`/?error=${encodeURIComponent(e.message)}`)}});
router.get('/logout',async(req,res)=>{await clearAuth();req.session.destroy(()=>res.redirect('/?message=Mercado Livre desconectado'))});
async function ensureToken(req,res,next){try{const source=sessionToAuth(req.session)||await loadAuth();if(!source)return res.redirect('/?error=Conecte o Mercado Livre primeiro');const a=await ensureFreshAuth(source);syncAuthToSession(a,req.session);next()}catch(e){res.redirect(`/?error=${encodeURIComponent(e.message)}`)}}
module.exports=router;module.exports.ensureToken=ensureToken;
